language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r crud *
  - mkdir -p deploy
  - mv crud.zip deploy/crud.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: crud-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: crud-build # S3 버킷
    key: crud.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: crud # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: crud-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

  # CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - minjea917@gmail.com
